version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    entrypoint: ["celery", "-A", "config", "worker", "-l", "INFO"]
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
